### ISSUE TITLE
Better documentation with examples

### ISSUE THREAD

**Issue by foresmac** [simplesamlphp/saml2#126]
@jaimeperez stated in https://github.com/simplesamlphp/simplesamlphp/issues/874#issuecomment-397609019:
> SAML is a quite complicated protocol. The SAML2 library is quite low level, and as such it shouldn't be used unless you have a very good knowledge of SAML as a protocol (as pointed out in the readme file), at which point the library itself is pretty much self-explanatory.

I have to disagree; I've read the spec, I know what I want to do, but even after digging through the code in this repo it's not entirely clear how I would go about doing so using the various bits and pieces. Confusingly (to me), stuff for making a response, adding assertion statements, signing the assertion, and then encrypting the assertion seem spread over multiple files. There doesn't appear to be any obvious or "self-explanatory" way to accomplish what I need to accomplish.

To be clear, I _do not_ need to have an actual functional separate IdP or SP service (which SimpleSAMLphp I think would provide); instead, a third-party I need to integrate with requires using SAML 2.0 to send a user over to their service to complete a transaction. All I need to do is generate the response with the requisite signature and encrypt it and send that payload to my user's browser. But to get all the necessary information into the assertion, I need to integrate with my Wordpress site.

What I would like to do is simply write a function that will generate the proper SAML response, embed that in an HTML form, and send it to my user when they click a particular button. All of the libraries I found (for both PHP and Python, since we have services written in Python as well) seem to be primarily geared towards implementing SP-related functions, so decryption, validating signatures, reading assertions, etc. Even the code here seems to be organized for that purpose, and less for going the other way: creating assertions, signing them, and encrypting them.

I have quite a bit of experience as a technical writer, so I'd be happy to contribute documentation if I had some idea of what steps were needed to accomplish the above.

**Comment by jaimeperez** [comment]
Hi @foresmac!

While improving the documentation and having better usage examples is something we always welcome, you are actually kind of proving my point. If you need to send a SAML2 response with an assertion to a service, you are an IdP. Note that SAML is not just a collection of messages that you can use the way you want to. If you need to send such response after the user clicks a button, that's called _IdP-initated authentication_, and is covered in [the documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-idp-more#section_4). In any case, you should be using SimpleSAMLphp, instead of implementing the SAML2 protocol yourself based on this library. If your existing wordpress is supposed to be your backend for authentication, then you need to write an authentication source that provides such integration with wordpress.

**Comment by foresmac** [comment]
I just gave up and wrote something using a Python binding to xmlsec that works for now. I suppose I could rewrite it using Rob's PHP library to do the same if given the time. Thanks anyhowways.

**Comment by jaimeperez** [comment]
I'd strongly recommend you to stop implementing your own SAML and use a full IdP (SimpleSAMLphp or whatever fits your environment). There might be lots of security mechanisms and protocol subtleties that you could be missing. I would also recommend you to **not** use xmlseclibs directly. It has security issues that haven't been fixed in a stable release yet.
