### ISSUE TITLE
Attributes sent without AttributeValues

### ISSUE THREAD

**Issue by gtkrug** [simplesamlphp/saml2#135]
Sometimes the attribute value for one of the attributes asserted by my Simple SAML IDP has no value in the user store (DB).  When this happens the SAML Assertion includes the saml:Attribute but the saml:AttributeValue is empty, for example:

``` xml
<saml:Attribute Name="sample" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
   <saml:AttributeValue xsi:type="xs:string"/>
</saml:Attribute>
```

It seems like the attribute should not be sent in this case, or at least there should be an easy option to not send attributes like this (as an attribute with no value could be interpreted incorrectly by some SPs and the IDP should have control over whether such attributes are released).

**Comment by thijskh** [comment]
A test with the example-userpass authsource with empty string attribute reveals that SSP sends it as a self-closing tag, which is not correct.

**Comment by thijskh** [comment]
So after some research into this:
- When given an empty string attribute value, SimpleSAML / saml2 will correctly generate an attributevalue with empty string content (`<saml:AttributeValue xsi:type="xs:string"></saml:AttributeValue>` and `<saml:AttributeValue xsi:type="xs:string" />` are equivalent in XML).
- When given a null value, it will produce the same with `xsi:nil` set to true.

This conforms completely to the spec, SAML 2.0 core 2.7.3.1.1:
```
If a SAML attribute includes an empty value, such as the empty string, the corresponding
<AttributeValue> element MUST be empty (generally this is serialized as <AttributeValue/>).
This overrides the requirement in Section 1.3.1 that string values in SAML content contain at least one
non-whitespace character.

If a SAML attribute includes a "null" value, the corresponding <AttributeValue> element MUST be empty and MUST contain the reserved xsi:nil XML attribute with a value of "true" or "1".
```

If the data source contains empty string values, I think it's correct that SimpleSAML assumes you want to send empty string values, since this is explicitly something that you are allowed to do. If you don't want this, this should be fixed in the source. Or in the corner case that you cannot fix your own attribute source, you can use an authproc filter to remove any of them before processing.

I have added test in our testsuite that verifies the described behaviour actually happens in f700b5663f1a5d2eb45e0c40f36fa07157d4440d.
