### ISSUE TITLE
Multiple <saml:AuthnStatement> not supported

### ISSUE THREAD

**Issue by JohanLindblad1** [simplesamlphp/saml2#136]
The Simplesamlphp SP does not accept multipe <saml:AuthnStatement>. Instead, it throws the following error:

```
Backtrace:
0 www/module.php:170 (N/A)
Caused by: Exception: More that one <saml:AuthnStatement> in <saml:Assertion> not supported.
Backtrace:
6 vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:384 (SAML2_Assertion::parseAuthnStatement)
5 vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:254 (SAML2_Assertion::__construct)
4 vendor/simplesamlphp/saml2/src/SAML2/Response.php:36 (SAML2_Response::__construct)
3 vendor/simplesamlphp/saml2/src/SAML2/Message.php:547 (SAML2_Message::fromXML)
2 vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:74 (SAML2_HTTPPost::receive)
1 modules/saml/www/sp/saml2-acs.php:31 (require)
0 www/module.php:127 (N/A)
```

**Comment by thijskh** [comment]
We've taken a look at this issue.

If we from the saml2 library perspective want to deal with multiple authnstatements this would mean we'd need to change the API significantly. Because things like AuhtenticatingAuthority, AuthnInstant, sessionNotOnOrAfter or sessionIndex are not exposed as arrays now but as single values. So this means quite some work and potential breakage by consumers.

Just taking the first one (or an arbitrary one) seems not satisfactory since there's nothing to say that this is the "correct" or "right" one to fill those values with.

Could you in any case provide an example of what such assertions look like?

**Comment by JohanLindblad1** [comment]
I am afraid I don´t have any examples saved from the prevoius problems we have found.

From what i remember, there was interesting content in all of the authnStatements as the would represent different steps of the autentication process. As 2-factor authentication is getting increasing attention I would assume there will be a need to access the content in all of the authnStatements.

**Comment by tvdijen** [comment]
This was solved in the new API in `master`. Not released yet.
