### ISSUE TITLE
phpmd: abandoned

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/saml2#147]
PHPmd seems pretty much abandoned (last version ~ 2yrs ago)..
Given the backlog on https://github.com/phpmd/phpmd, we may want to investigate alternatives
This is especially worrying now that we're moving towards 4.0 / PHP7..

During development I've encountered an issue with phpmd, ultimately their dependencies phpdepend and symfony/dependency-injector:  https://github.com/pdepend/pdepend/issues/368

**Comment by tvdijen** [comment]
Okay, so the issue appears to be as follows:
PHP7 & PHPmd == Symfony4 being used by PHPdepend.

Symfony4 does not support HVVM [anymore](https://symfony.com/blog/symfony-4-end-of-hhvm-support) == tests fail...

We need to decide whether we:
1. keep calm and drop support for HVVM, or
2. find an alternative for (abandoned) PHPmd that doesn't rely on Symfony

I'd opt for 2, because I hate to rely on abandoned code

**Comment by tvdijen** [comment]
After some more investigation, I'd like to opt for removing phpmd completely.. We already use phpcs that should be able to catch the same coding issues as phpmd used to

**Comment by tvdijen** [comment]
Trouble not yet, but it will when we start working towards a 4.0 release...
It's hard for me to tell what the reason was to add it, because it was added 5 years ago without clear description.. PHPcs is good enough I think and we can use other external tools like Scrutinizer as they don't require anything..

**Comment by jaimeperez** [comment]
Yes, let's not waste our time with abandonware...

What we should probably do is to add psalm (or phpstan, maybe?) as a dev dependency, and start using it to uncover possible bugs...

**Comment by tvdijen** [comment]
Psalm seemed very promising on simplesamlphp, until we had to stop upgrading because of PHP7-dependencies and their insane release-rate.. We could give it another shot I guess.. I'm personally a big fan of phpcs and scrutinizer (although they have different interpretations of the PSR2-standard)

I guess it's not up to me what to use, but for now it's clear that we drop phpmd..

**Comment by jaimeperez** [comment]
I'm not particularly a huge fan of Scrutinizer. I added it some time ago and almost never use it nowadays, for two reasons:

- It apparently misses issues and warns you about them in totally unrelated commits. As in, there's an issue in class `A` but it doesn't notice. Then you fix another issue in class `B`, and then Scrutinizer notices the one in `A` (even though you didn't even touch that file) and tells you your commit solved an issue in `B` but introduced another in `A` (which isn't true).

- The logic to follow user-provided data through the code is not very well polished. We tend to get lots of warnings about alleged security issues (XSS) because some data from `$_REQUEST` or `$_SERVER` is supposedly ending up in the state array (when it's actually not) and then being printed to standard output or stored in a database (which isn't true in some occasions either).

Anyway, my two cents. In my opinion, it helps identifying trivial mistakes, but introduces a lot of noise and false positives too. That's in a way why I'm also eager to introduce static analysis, because it'll help us check the code much more thoroughly and deeply than any of these tools.

**Comment by jaimeperez** [comment]
It's not an issue in the SAML2 library, it's an issue in XMLSecLibs. The `XMLSecEnc` class does not include a `use DOMElement;` statement, and therefore all the uses of `DOMElement` in the class without a namespace are assumed to be in the `RobRichards\XMLSecLibs` namespace...

**Comment by tvdijen** [comment]
Ah, that makes sense! But it feels like an unwanted feature to me if our tests start to fail because our dependencies mess up..

**Comment by jaimeperez** [comment]
Indeed. If we want this to be used during the build, we need to find a way to disable errors triggered by dependencies.

**Comment by tvdijen** [comment]
I have tried several things, but I can't make it work...

**Comment by jaimeperez** [comment]
Do you mean that the build keeps failing because of external dependencies? Or that it fails because of errors on our code base?

**Comment by tvdijen** [comment]
I can't make it to ignore the external dependencies..

**Comment by jaimeperez** [comment]
I've had a look and I think it is indeed working as expected (although I don't know if that's a consequence of your very last commit, I haven't looked into past builds).

In any case, psalm is failing because of errors on our side. I've just committed fixes for a bunch of issues there, and will keep working on it.

**Comment by jaimeperez** [comment]
Then it was the previous one, but I'm quite sure that it actually worked fine! 😄

**Comment by jaimeperez** [comment]
I just pushed one more, but that'll be it for the day...
