### ISSUE TITLE
Unable to Validate SHA512 due to static Assertion

### ISSUE THREAD

**Issue by markhuot** [simplesamlphp/saml2#188]
Related to #124, I have a SHA512 key coming through SAML that is getting passed through to `SAML2/Assertion::validate`, here,

https://github.com/simplesamlphp/saml2/blob/121aec484db5331d2c743f4ce89c42b9be3f8127/src/SAML2/Assertion.php#L669

Once my code hits `Assertion::validate` it fails because there is the static expectation for a SHA256 key. Is there a better or different way to validate my key without hitting this static validation?

I see that this might not be how it's supposed to work from here,

https://github.com/simplesamlphp/saml2/commit/43590bc9614c1df5bd7b1639088f7d904842892b

Happy to provide more detail, as needed, but I'm not sure if this is a bug or a failure in my implementation.

Thank you!

**Comment by jaimeperez** [comment]
Hi @markhuot,

This is not the case. xmlseclibs mandates the `XMLSecurityKey` object to be created passing an algorithm. We bumped the algorithm to `RSA_SHA256` by default, but that doesn't mean the only algorithm supported is the default `RSA_SHA256`, nor that it is hardcoded in any way. [Later in the code](https://github.com/simplesamlphp/saml2/blob/master/src/SAML2/Utils.php#L199) the algorithm is changed to whatever was specified in the signature, in case it is different to this default `RSA_SHA256`.

Therefore, it is perfectly possible to validate signatures with `RSA_SHA512` and other algorithms. If validation is failing, it is likely due to a configuration error on either side.

**Comment by markhuot** [comment]
Thanks for the quick response @jaimeperez! I'm integrating with SAML via this plugin: https://github.com/flipboxfactory/saml-sp

I'm trying to parse through the plugin and submit a PR to fix up a bug in the plugin but I don't think I'm understanding the xmlseclibs approach.

In other words, when the SAML response comes back the plugin takes the response and calls `->validate()` with the key. That key is SHA512, so when it hits this code it fails. Should the plugin be calling `->validate()` in a different way? The call is here. It seems like the plugin is taking the keys in the response and trying to `->validate()` each of them.

https://github.com/flipboxfactory/saml-core/blob/fe8c7e105efccd63aa00350bac0b2634dc96b493/src/validators/SignedElement.php#L34

Thank you for any help you can provide, I realize this is outside the scope of the SAML lib.

**Comment by jaimeperez** [comment]
Hi,

If this plugin you are using is not creating a key with the appropriate algorithm before validating, then it's of course wrong. You need to parse the incoming signature, process the algorithm specified on it, and then create a key with it, paying special attention to the algorithm being a public key one.

**Comment by markhuot** [comment]
Thanks @jaimeperez, I think the issue is that the plugin was incorrectly determining the certificate algo. I worked with the plugin developer to fix this up. Thank you for your responses, they helped determine where the plugin was failing.
