### ISSUE TITLE
Class "SAML2\Constants" not found

### ISSUE THREAD

**Issue by happydude** [simplesamlphp/saml2#357]
I'm seeing an issue in the latest tag from 4.6.11 to 4.6.12 causing an issue in simplesamlphp

simplesamlphp/simplesamlphp/modules/saml/src/Auth/Source/SP.php:77

Class "SAML2\Constants" not found

If I revert back to 4.6.11 it works again

I noticed in my composer.lock the autoload value changed
`"SAML2\\": "src/SAML2"` to `"SimpleSAML\\SAML2\\": "src/SAML2"`

**Comment by tvdijen** [comment]
This can only happen if you install unreleased versions of SimpleSAMLphp.
The change you see means you're updating beyond 4.x.. That's 5.x development code.

**Comment by happydude** [comment]
My lock file shows simplesamlphp/simplesamlphp v2.2.1

**Comment by tvdijen** [comment]
It all makes zero sense, sorry..

**Comment by happydude** [comment]
I'm not a pro at github but this looks to me like the tag has v5 stuff in it https://github.com/simplesamlphp/saml2/compare/v4.6.11...v4.6.12

I'm going by the compose docs that say: `^1.2.3 is equivalent to >=1.2.3 <2.0.0`

**Comment by gravelpot** [comment]
@tvdijen This issue should be re-opened ASAP. We had a site auto-update to include `simplesaml/saml2` to 4.6.12 and we are experiencing the same error.

**Comment by happydude** [comment]
@gravelpot I think the tag has been fixed,  it is working for me now, try another `composer update`

**Comment by gravelpot** [comment]
Hmmm... so that `4.6.12` tag was deleted and then re-created to point to a different commit?

If so, I think that should have been a new tag. I don't know enough about Composer to know for sure, but if `composer update` is just looking for a version number change, anyone who has already updated is not going to get the new, fixed tag.

It would have been cleaner to just do a `4.6.13` tag, rather than rewrite the already published git history.
