### ISSUE TITLE
Documentation: dateTime "time zone component"

### ISSUE THREAD

**Issue by relaxnow** [simplesamlphp/saml2#39]
The last 2 prs we have had ( https://github.com/simplesamlphp/saml2/pull/36 and https://github.com/simplesamlphp/saml2/pull/38 ) have both been for allowing the ommission of the timezone 'Z' in datetimes.

While this appears to be a bug in the spec it's clear that there are faulty implementations out there. As someone who is often asked to 'just make things work' I very much favor the [Robustness principle](http://en.wikipedia.org/wiki/Robustness_principle) here. Otherwise we might be encouraging developers to fork.

We could introduce a configuration option "Non Standard Date Time" and make the SAML2 lib use a different strategy for parsing date times if that is set?
At least we should document this more clearly in the code.

**Comment by thijskh** [comment]
We ran into the issue a couple of times in our federation and every time it was possible to fix the faulty implementation, thereby improving things for everyone.

I'm not a firm believer of the Robustness principle because it hides bugs and makes behaviour less predictable: if SAML implementations are forgiving, a product working with implementation A does not necessarily work with implementation B since they may have different way of being "lenient".

HTML has shown that now everyone is much more into strict standards adherence, things got much simpler and actually even more interoperable than in the times of a browser just accepting anything that remotely looked like html.

If this bug is widespread in implementations a switch or other way to at least know about the problem if you want to know about it may be acceptable.

**Comment by jaimeperez** [comment]
I agree with Thijs here. The spec is pretty clear with regard to the use of timezones (or maybe I should just say to **not** use them), and everyone using timezones in SAML messages is breaking the spec.

We could of course be "gentle" and allow timezones in SAML messages, but then all of a sudden we have yet another thing to worry about: comparing dates with timezones is not the same as comparing dates without them.

To put it this way: I'm not worried about forks (should I? Is that a bad thing?). I'm worried though about people stopping to adhere to the specs just because *things kept working*. I'm worried too about things not working, ruining interoperability between products with unpredictable behaviours just because people stopped following the specs.

So my vote (which should not be considered final, in any case) goes for keeping compliance with the spec. Let's see what others think.

**Comment by jaimeperez** [comment]
Oh, and by the way. I realize how hypocritical my comment is given the use we are doing of `RelayState` :smile:

**Comment by relaxnow** [comment]
> HTML has shown that now everyone is much more into strict standards adherence, things got much simpler and actually even more interoperable than in the times of a browser just accepting anything that remotely looked like html.

Actually the 'strict' approach was XHTML which failed spectacularly, the only thing HTML5 did was normalise what everyone was already doing with malformed input.

I'm not arguing for accepting non timezoned dates by default, but allowing patches that add a configurable mode that does accept faulty dates.
Our answer now is basically "fix your faulty implementation or fork".

It may not always be possible to fix faulty implementations because they are owned and operated by third parties and running a forked SSP is dangerous because you stray from the update path.

Then again guys have way more experience with real world deployments, so if you say it's not an issue in practice then I'll defer to your judgement.

Regardless we should add a comment pointing to this discussion for future reference.

**Comment by thijskh** [comment]
At least my experience has been that any faulty implementations we encountered with this could actually be fixed and have actually been fixed...

**Comment by jaimeperez** [comment]
Thanks Thijs! :smile:
