### ISSUE TITLE
Issue processing unsigned Response

### ISSUE THREAD

**Issue by ajmichels** [simplesamlphp/saml2#73]
I get the following exception if I attempt to process a Response that is not signed. `Uncaught exception 'SAML2\Response\Exception\UnsignedResponseException' with message 'Both the response and the assertion it containes are not signed.' in .../vendor/simplesamlphp/saml2/src/SAML2/Response/Processor.php:150`

I should be able to process unsigned responses, right?

Using simplesamlphp/saml2 v2.2 on PHP 5.4.45

**Comment by ajmichels** [comment]
It seems like it would be better to log a warning rather than force Responses to be signed. If not that then it shouldn't be possible to make unsigned Responses with this library. Right now you have to explicitly call `setSignatureKey()` to sign the Response but if you don't everything works fine, you get a valid Response.

**Comment by thijskh** [comment]
Thanks. Can you clarify which profile you're using where unsigned responses are in play?

**Comment by ajmichels** [comment]
I am not sure what you mean by "profile". Here is the code I am working through [https://github.com/ajmichels/saml-proof](https://github.com/ajmichels/saml-proof). It's just a proof for a larger project involving an existing code base.

**Comment by thijskh** [comment]
There's a list [at Wikipedia](https://en.wikipedia.org/wiki/SAML_2.0#SAML_2.0_Profiles). I'm asking because in the most common WebSSO profile, or any profile that uses the frontend channel via the web browser, there's no use to using assertions that are unsigned (both the assertion and the response it's contained in) because it negates the security of the protocol. So if you're in need of unsigned assertions, I'm curious of the use case you're after.

**Comment by ajmichels** [comment]
The biggest use case I currently have is testing. Signatures is just another layer of complexity when attempting to test and debug something. If it is't required by the protocol and is only there to enhance the security of the protocol then it would be very useful to be able to disable it at will to reduce complexity whenever needed.

**Comment by thijskh** [comment]
I'm not sure I agree. Adding the ability to disable signatures adds complexity with its risks and maintenance required, affecting all users. Arguably indeed it now adds complexity when testing, but I believe that to be a better place to have the complexity rather than in the code paths used in production. Especially since you'll need to converge to a situation anyway where you'd need to be checking signatures, so it will only save some complexity in the short run, while configuration in the library is there in the long run.

Also, the mere presence of such an option inevitably leads to someone using that when they should in fact be checking signatures, a bit like CURLOPT_SSL_VERIFYPEER which has been found in numerous projects being enabled unintendedly in production setups as a leftover from testing. Surely we cannot prevent everyone from shooting themselves in the foot, but this is an additional argument about why I'm hesitant about this.

**Comment by jaimeperez** [comment]
I fully agree with Thijs on this 👍
