### ISSUE TITLE
Signature required even for HTTP-Redirect Response

### ISSUE THREAD

**Issue by artem-tim** [simplesamlphp/saml2#82]
Hello,
I stumbled upon what appears to be a bug to me, please correct me if I'm wrong.
According to the specs, the AuthnResponse is not required to carry the signature inside the SAML message itself in the case of HTTP-Redirect (where the signature can be done via the query parameters). Actually, an IDP implemented with this library does precisely that : when generating an AuthnResponse using Redirect binding, the SAMLResponse body is left unsigned while the signature correctly appears among query parameters (comparing HTTPRedirect.php and HTTPPost.php).
The problem is, when such Response is treated by the lib, the Response/Processor isn't happy if there is no signature either at root or in assertions, whereas this response does comply with the specification and carries the signature in the query parameters.
I didn't start a discussion over a pull request because I'm not sure which is the best solution, but the ones I am thinking about are : 

1. Simply remove the whole block `if (!$response->isMessageConstructedWithSignature())` in Response/Processor::verifySignature. The HTTPRedirect adds the correct validator from query params to the Message so if it's invalid there will be an Exception anyway (I checked)
2. In a similar manner, remove the check in Response/Processor::verifySignature
3. If there is a real need to keep the verifications above, add a method (Message.php) to check if there is a validator based on function name ("validateSignature"), and add it as requirement to be unhappy along one of the verifications above.

Anyway, even though HTTP-Post is more common because of the length that can attain the encoded SAML message, in my humble opinion HTTP-Redirect deserves some love too - but maybe I'm missing something here.

Best regards,
Artem

**Comment by pmeulen** [comment]
Hi Artem,

Sending SAML a Response via HTTP-Redirect would be unusual, it is not defined in the Web-SSO profile which states "Either the HTTP POST, or HTTP Artifact binding can be used to transfer
the message to the service provider through the user agent" (see: https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf). So I'm not surprised that the code currently assumes that a response is signed using XML-DSIG, as this is what these other bindings use.

The HTTP-Redirect binding is indeed defined for a SAMLResponse in https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf so it can be implemented based on that definition.

I'm curious as to why you want to do this? Do you have an IdP that sends responses using a HTTP-Redirect binding?

**Comment by artem-tim** [comment]
Hi Pieter,

You are right, the standard SAML profile discourages the use of HTTP Redirect (strongly saying "it should NOT be used"). However the profile being a set of recommended usage rules, the SAML specification itself still considers this possibility (https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) : 

> The HTTP Redirect binding is intended for cases in which the SAML requester and responder need to communicate using an HTTP user agent (as defined in HTTP 1.1 [RFC2616]) as an intermediary. This may be necessary, for example, if the communicating parties do not share a direct path of communication.
> It may also be needed if the responder requires an interaction with the user agent in order to fulfill the request, such as when the user agent must authenticate to it.

As for my usecase, I simply want my sso (which uses your awesome library) to let users choose their preferred way.
Ultimately, it boils down to whether you decide your library should support HTTP Redirect or not. For me it looked like you do, because there you already implement everything to use it : correct information encryption in url parameters, correct signature generation, issuing the correct corresponding request or response, and such. Literally the only thing that separated the support for HTTP Request is this signature presence in the message body - and I made tests of my sso acting as both IDP or SP in both modes (Post&Redirect) after cancelling this particular check. That is why I was under the impression it was a bug.

Best regards,
Artem

**Comment by pmeulen** [comment]
Thanks for your clarifications. Whether this is a bug is a matter of expectations. I do not expect this library to be a fully complete implementation of the entire SAML specification. I expect it to implement the functionality that is being used. So I do not see it as a bug. That is why a asked you for why you would want to use this. Adding this feature will take time: yours, ours and probably also in the future to maintain this. The changes will be in an area of the code where I want to be careful because of the risks of introducing security bugs. Don't forget about writing test cases and reviewing. So before implementing this I want to verify that it is actually useful to users of the library. I.e. will be used?

It is regarding this usefulness that I have my doubts:

- IdP implementations are unlikely to support it
- It duplicates what the POST binding offers in an inferior way

**Comment by jaimeperez** [comment]
Hi @artem-tim!

I have a couple of doubts:

* When you say _let users choose their preferred way_, do you actually refer to end users? As in, letting them use HTTP-POST or HTTP-Redirect to their will? If that's the case, that's not something for the end user to decide. The binding used is something that should be agreed between the SAML entities, and there are very good reasons why the standard uses HTTP-POST for SAML responses instead of HTTP-Redirect.

* This makes me wonder too about your deployment. It looks like you are implementing an IdP yourself by using this library, but this library is providing only the core SAML functionality, skipping much of the logic involved in the protocol and required to be compliant with the standard (not to talk about all the security checks and mechanisms that are required and that you would need to implement manually). Therefore, we usually recommend **not** using the library directly but SimpleSAMLphp instead. Is there any reason why you are implementing a full SAML IdP yourself instead of just using SimpleSAMLphp?

**Comment by artem-tim** [comment]
Hello @jaimeperez

I understand your questions. To clarify my intent, I am developing a SAML based SSO option for a CMS system (which strives to provide services beyond those of a simple CMS). Therefore, when I refer to "users", I mean web platforms which implement our CMS. They may choose or not to become IDP or SP for their own systems, this is why I am trying to provide options they may require. But as Pieter said, this may actually not be a wanted option since it is indeed inferior to using POST. Thing is, as you know users are picky, and I would not be surprised if some had weird limitations over the way of data transmission...

Also, as I said, your library has all the code needed. Therefore the implementation effort seems minimal - it is a matter of an if/then/else to put in a smart place. But indeed, is it worth the trouble going through the integration process with tests and security analysis? I'm not sure either.

**Comment by pmeulen** [comment]
Hi Tim,

I'm closing this issue. Feel free to reopen it if you have a use for this feature, or if you see it causing a problem for you!
