### ISSUE TITLE
Migrate assertions to something more modern

### ISSUE THREAD

**Issue by DRvanR** [simplesamlphp/saml2#90]
The SAML2 library liberally uses the [`assert`][1] function as an assertion (sort of guard clause). Starting PHP7, this function has been changed to have a possible different implementation, that of [defining an expectation][2], with the ability to preserve the behavior of earlier versions.

Starting in PHP 7.2 the old behavior [will be deprecated][3]. Since PHP 5.6 is now [security support only][4] and PHP7.1 is considered the current stable version, SAML2 should start working on PHP7 compatibility.

My suggestion would be to remove all assert statements and replace them with as much typehints as possible and use [beberlei/assert][5] for any other assert statements.

[1]: https://github.com/simplesamlphp/saml2/search?utf8=%E2%9C%93&q=assert+path%3Asrc&type=Code
[2]: http://php.net/manual/en/function.assert.php#function.assert.expectations
[3]: https://wiki.php.net/rfc/deprecations_php_7_2#assert_with_string_argument
[4]: http://php.net/supported-versions.php
[5]: https://github.com/beberlei/assert

**Comment by thijskh** [comment]
:+1:

**Comment by jaimeperez** [comment]
Agreed.

I'm afraid we'll still be stuck for a while supporting older versions of PHP, but we also need to be fully compatible with newest versions anyway. I've always found asserts dangerous since they'll work only depending on your configuration, so I fully agree with using type hinting when possible and delegate further checks to an external dependency.

I took a look at [ihor/nspl](https://github.com/ihor/Nspl) some time ago indeed, but unfortunately, I found it just didn't work for me. Now I was trying it again and there seems to be some mess with the namespaces, and constants or function names are not found if you don't explicitly use the namespaces.

I've also taken a brief look at [beberley/assert](https://github.com/beberlei/assert) now, and I miss the possibility to have parameters that can be of several types (different than _null or..._). I'm not sure how much of those we have in the SAML2 library, but we have a lot of them in SimpleSAMLphp and I would definitely like to reuse the same dependency. The same problem affects [webmozart/assert](https://github.com/webmozart/assert), which is a fork of the previous and seems much more popular.

The only "reasonable" alternative I see is [wikimedia/assert](https://github.com/wikimedia/Assert), though the fact that they use the github repo as a mirror, that they have only released "betas", and that they are not actively developing it, makes me a bit afraid of using it, even though it looks much more flexible than the others...

**Comment by DRvanR** [comment]
> I miss the possibility to have parameters that can be of several types (different than null or...)

That sounds like a prime case for method overloading (which we don't have :disappointed: ) and could be achieved in different ways (for instance, delegation based on type of parameter) so that asserts & typehints can be used.

To me webmozart of beberlei does not matter, I've used both, and they're mostly the same. Both are good. The wikimedia is just a wrapper with some magic around `if (! someclause) { throw exception() }` and does not seem to actually offer anything to me (must admit only looked briefly though due the concerns of @jaimeperez :wink: )

**Comment by jaimeperez** [comment]
Indeed, _wikimedia/assert_ is quite basic, pretty much just a substitution for standard calls to `assert()`, where you have to do the checks yourself. That makes it more flexible, though.

I don't have strong feelings about one or another library either. I would just want to have something simple that covers what we need, and stick to that.

**Comment by thijskh** [comment]
The concrete deprecation issue has been fixed now. Remains the question of removing asserts altogether.

**Comment by tvdijen** [comment]
Now that work on a PHP7+ branch has started, it may be the right time to pick one package to replace the remaining assert()s.. Anything that could be replaced with a typehint is already gone on the release-4-alpha branch

**Comment by jaimeperez** [comment]
Tim, how many calls to `assert()` are left after adding type hints? It would be interesting to take a look at them, see what kind of tests we are still doing, and try to decide based on that.

**Comment by tvdijen** [comment]
We went from to 228 > 160 and what's left is mostly the toXML-methods testing all object-properties before actually generating XML.

**Comment by tvdijen** [comment]
I've been looking into this a bit more and I think that the majority of the asserts can actually be removed.. Most of them are in the toXML-methods to verify property-content before generating XML.
However, there's just no way of setting some stupid value any more.. You always have to go through the constructor or through the getter/setters (once we convert public properties to private/protected).

**Comment by tvdijen** [comment]
Exactly, so that's what I did in the `assertions`-branch.. Only a few assertions left that test for non-empty arrays because a field is mandatory, the rest could all be removed..
I can add a PR if you like, unless you still want to consider other assertion-libraries?

**Comment by jaimeperez** [comment]
I'd like to take a look at _beberlei/assert_, since I'm not familiar with it, but unless it's clearly missing something basic, I probably won't have any strong opinions about it...

**Comment by tvdijen** [comment]
One thing you mentioned earlier is the ability to test a variable for 'one of many not null' types.. I haven't found a way to create a 'logical OR', but the quick & dirty workaround is to do
`Assertion::true(is_bool($x) || is_string($x))`

I had to use it a few times, but I don't really see it as a problem..

**Comment by jaimeperez** [comment]
That can be fixed with the `nullOr*()` methods provided by the API 😄
